name: MonoGS
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cudatoolkit
  - plyfile=0.8.1
  - python=3.11.0
  - pip=23.3.1
  - pytorch=2.2.0
  - torchaudio=2.2.0
  - torchvision=0.17.0
  - tqdm
  - pytorch-cuda=12.1
  - pip:
    - submodules/simple-knn
    - submodules/diff-gaussian-rasterization
    - opencv-python==4.8.1.78
    - munch
    - trimesh
    - evo==1.11.0
    - open3d==0.18.0
    - torchmetrics
    - imgviz
    - PyOpenGL
    - glfw
    - PyGLM
    - wandb
    - lpips
    - rich
    - ruff
    - matplotlib==3.5.3