inherit_from: "configs/mono/tum/base_config.yaml"

Dataset:
  dataset_path: "datasets/tum/rgbd_dataset_freiburg2_pioneer_slam3"
  Calibration:
    fx: 520.90862
    fy: 521.007327
    cx: 325.141442
    cy: 249.701764
    k1: 0.2312
    k2: -0.7849
    k3: 0.9172
    p1: -0.0033
    p2: -0.0001
    width: 640
    height: 480
    depth_scale: 5000.0
    distorted: True
