Results:
  save_results: True
  save_dir: "results/kitti"
  save_trj: True
  save_trj_kf_intv: 10
  use_gui: True
  eval_rendering: False
  use_wandb: False

Dataset:
  type: 'kitti'
  sensor_type: 'monocular'
  pcd_downsample: 64
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.01

Training:
  init_itr_num: 1500  # Increased for better initialization
  init_gaussian_update: 200  # Increased for more frequent updates
  init_gaussian_reset: 600  # Adjusted reset frequency
  init_gaussian_th: 0.01  # Adjusted threshold
  init_gaussian_extent: 20  # Reduced extent
  tracking_itr_num: 300  # Increased iterations for better tracking
  mapping_itr_num: 300  # Increased iterations for better mapping
  gaussian_update_every: 100  # More frequent updates
  gaussian_update_offset: 50  # Adjusted offset
  gaussian_th: 0.8  # Increased threshold for updates
  gaussian_extent: 1.5  # Increased extent for updates
  gaussian_reset: 2000  # Adjusted reset frequency
  size_threshold: 10  # Lowered threshold for keyframe size
  kf_interval: 3  # Reduced interval to capture more keyframes
  window_size: 10  # Increased window size for optimization
  pose_window: 4  # Increased pose window for optimization
  edge_threshold: 1.2  # Increased edge detection threshold
  rgb_boundary_threshold: 0.02  # Increased RGB boundary detection threshold

  kf_translation: 0.06  # Reduced translation threshold for keyframe insertion
  kf_min_translation: 0.03  # Reduced minimum translation for keyframe insertion
  kf_overlap: 0.9
  kf_cutoff: 0.3
  prune_mode: 'slam'
  single_thread: False
  spherical_harmonics: False

  lr:
    cam_rot_delta: 0.006  # Increased learning rate for camera rotation
    cam_trans_delta: 0.004  # Increased learning rate for camera translation

opt_params:
  iterations: 3500  # Increased for more robust optimization
  position_lr_init: 0.001  # Adjusted initial learning rate
  position_lr_final: 0.000001  # Adjusted final learning rate
  position_lr_delay_mult: 0.01  # Same delay multiplier
  position_lr_max_steps: 35000  # Increased max steps for learning rate decay
  feature_lr: 0.003  # Increased feature learning rate
  opacity_lr: 0.04  # Adjusted opacity learning rate
  scaling_lr: 0.001  # Same scaling learning rate
  rotation_lr: 0.001  # Same rotation learning rate
  percent_dense: 0.02  # Increased percentage of dense points
  lambda_dssim: 0.3  # Increased DSSIM loss weight
  densification_interval: 200  # Increased interval for densification
  opacity_reset_interval: 3500  # Increased reset interval for opacity
  densify_from_iter: 1000  # Adjusted starting iteration for densification
  densify_until_iter: 20000  # Adjusted ending iteration for densification
  densify_grad_threshold: 0.0001  # Adjusted gradient threshold for densification

model_params:
  sh_degree: 1  # Increased SH degree for more detail
  source_path: ""  # Set if using pretrained models
  model_path: ""  # Set if saving/loading models
  resolution: -1  # Set to desired resolution for KITTI images
  white_background: False  # Same background setting
  data_device: "cuda"  # Ensure using GPU for better performance

pipeline_params:
  convert_SHs_python: False  # Same setting
  compute_cov3D_python: False  # Same setting
