Results:
  save_results: True
  save_dir: "results/kitti-mono/06"
  save_trj: True
  save_trj_kf_intv: 10 
  use_gui: False
  eval_rendering: False
  use_wandb: False

Dataset:
  type: 'kitti'
  sensor_type: 'monocular'
  pcd_downsample: 64
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.01

Training:
  init_itr_num: 1050 # improve the initial pose estimation
  init_gaussian_update: 100
  init_gaussian_reset: 500
  init_gaussian_th: 0.005
  init_gaussian_extent: 30
  tracking_itr_num: 100 # ehance the pose estimation
  mapping_itr_num: 150 # better mapping quality 
  gaussian_update_every: 150 # update the Gaussians more frequently.
  gaussian_update_offset: 50
  gaussian_th: 0.7 # for a stricter threshold, can reduce noise 
  gaussian_extent: 1.0 #  to improve the coverage of the Gaussians. 
  gaussian_reset: 2001
  size_threshold: 20
  kf_interval: 5
  window_size: 8 # to allow more frames in the optimization process.
  pose_window: 3
  edge_threshold: 1.1
  rgb_boundary_threshold: 0.01

  kf_translation: 0.08 # to ensure more keyframes are added during subtle movements.
  kf_min_translation: 0.05 # to ensure more keyframes are added during subtle movements.
  kf_overlap: 0.9
  kf_cutoff: 0.3
  prune_mode: 'slam'
  single_thread: False
  spherical_harmonics: False

  lr: # for finer pose adjustments, improving overall accuracy 
    cam_rot_delta: 0.003 
    cam_trans_delta: 0.001

opt_params:
  iterations: 30000
  position_lr_init: 0.0016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002

model_params:
  sh_degree: 0
  source_path: ""
  model_path: ""
  resolution: -1
  white_background: False
  data_device: "cuda"

pipeline_params:
  convert_SHs_python: False
  compute_cov3D_python: False