inherit_from: "configs/mono/kitti/base_config_03.yaml"


Dataset:
  dataset_path: "datasets/kitti/03"

  Calibration:
    fx: 721.5377
    fy: 721.5377
    cx: 609.5593
    cy: 172.854
    k1: 0.0
    k2: 0.0
    k3: 0.0
    p1: 0.0
    p2: 0.0
    width: 1242
    height: 375
    distorted: False