inherit_from: "configs/mono/kitti/base_config.yaml"

# cambiare il nome della sequenza => da 04 a 12

Dataset:
  # dataset_path: "/media/castor/Seagate-Basic/kitti_dataset/dataset/sequences/06"
  # devo fare 4, 6, 7
  dataset_path: "/media/castor/Seagate-Basic/kitti_dataset/data_odometry_color/dataset/sequences/03"

  Calibration:
    fx: 721.5377
    fy: 721.5377
    cx: 609.5593
    cy: 172.854
    k1: 0.0
    k2: 0.0
    k3: 0.0
    p1: 0.0
    p2: 0.0
    width: 1242
    height: 375
    distorted: False
  # start_idx: 100