inherit_from: "configs/mono/kitti/base_config.yaml"

# cambiare il nome della sequenza => da 04 a 12

Dataset:
  # dataset_path: "/media/castor/Seagate-Basic/kitti_dataset/dataset/sequences/04"
  # devo fare 4, 6, 7
  dataset_path: "/media/castor/Seagate-Basic/kitti_dataset/data_odometry_color/dataset/sequences/04"

  Calibration:
    fx: 707.0912
    fy: 707.0912
    cx: 601.8873
    cy: 183.1104
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 1226
    height: 370
    distorted: False
  # start_idx: 100