Results:
  save_results: True
  save_dir: "results/stereo-zed2"
  save_trj: True
  save_trj_kf_intv: 10
  use_gui: True
  eval_rendering: False
  use_wandb: False

Dataset:
  type: 'zed-stereo'
  sensor_type: 'stereo'
  pcd_downsample: 64
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.01

Training:
  edge_threshold: 1.1
  gaussian_extent: 1.2
  gaussian_reset: 2001
  gaussian_th: 0.7
  gaussian_update_every: 150
  gaussian_update_offset: 50
  init_gaussian_extent: 30
  init_gaussian_reset: 500
  init_gaussian_th: 0.005
  init_gaussian_update: 100
  init_itr_num: 1050
  kf_cutoff: 0.3
  kf_interval: 2
  kf_min_translation: 0.08
  kf_overlap: 0.9
  kf_translation: 0.1
  lr:
    cam_rot_delta: 0.0015
    cam_trans_delta: 0.007
  mapping_itr_num: 150
  pose_window: 3
  prune_mode: slam
  rgb_boundary_threshold: 0.01
  single_thread: false
  size_threshold: 20
  spherical_harmonics: false
  tracking_itr_num: 100
  window_size: 8
opt_params:
  densification_interval: 100
  densify_from_iter: 500
  densify_grad_threshold: 0.0002
  densify_until_iter: 15000
  feature_lr: 0.0025
  iterations: 30000
  lambda_dssim: 0.2
  opacity_lr: 0.05
  opacity_reset_interval: 3000
  percent_dense: 0.01
  position_lr_delay_mult: 0.01
  position_lr_final: 1.6e-06
  position_lr_init: 0.0016
  position_lr_max_steps: 30000
  rotation_lr: 0.001
  scaling_lr: 0.001

model_params:
  sh_degree: 0
  source_path: ""
  model_path: ""
  resolution: -1
  white_background: True
  data_device: "cuda"

pipeline_params:
  convert_SHs_python: False
  compute_cov3D_python: False
