inherit_from: "configs/mono/zed/base_config.yaml"

# Config for ZED stereo camera
# fps is 15
# in questo file ci sono i parametri presi dal file ufficiale delle zed 
# sono i parametri della camera left 
Dataset:
  dataset_path: "datasets/zed2/zed2"

  Calibration:
    fx: 264.88
    fy: 264.6325
    cx: 339.8725
    cy: 190.52025
    k1: 0.0432415
    k2: 0.0118588
    k3: -0.00551761
    p1: -0.000508506
    p2: -7.31961e-05
    width: 640
    height: 360
    depth_scale: 1000
    distorted: false